### ISSUE TITLE
mpileup: invalid option -- '@' 

### ISSUE THREAD

**Issue by Zoe133** [mgaynor1/nQuack#2]
hello，when I used inst/extdata/rawdata to prepare data, step 1 of Data processing with nQuack, I met an error : "mpileup: invalid option -- '@' ", so how can i fix it? Looking forward to your reply as soon as possible, thanks a lot.

**Comment by mgaynor1** [comment]
I replied to your email too quick! I thought that this was an issue with the samtools install, however this is not an issue with samtools. This was an issue with a system command in the `prepare_data()` function.  I thought this could be multi-threaded and it cannot be. 


This function has now been updated and should work.

**Comment by mgaynor1** [comment]
And the new push passed my git check! Closing this issue. Please let me know if you run into any other errors.

**Comment by Zoe133** [comment]
> I replied to your email too quick! I thought that this was an issue with the samtools install, however this is not an issue with samtools. This was an issue with a system command in the `prepare_data()` function. I thought this could be multi-threaded and it cannot be.
> 
> This function has now been updated and should work.

Thank you so much for the speedy reply. The issue has been solved.
