### ISSUE TITLE
"function cannot be evaluated at initial parameters" for beta distributions

### ISSUE THREAD

**Issue by RSchley** [mgaynor1/nQuack#4]
Hi there, 

I am inferring ploidy for tropical trees (specifically, putative tetraploid species) using both whole-genome resequencing data at 30-40x, as well as target-capture data for 1320 loci. I have previously prepared the data with **nQuire create**, **nQuire view** and **nQuire denoise**. I then run the output of denoise through the nQuack function `process_nquire(paste0(inpathtext, samp))`
 

When I run the model comparison from the nQuack tutorial on my own data like this:

```
for(i in 1:length(samples)){
print(paste0("Running ", samples[i]))
temp <- as.matrix(read.csv(paste0("./nQuack/03_processed/", samples[i], "_denoised_processed.csv")))
out1 <- quackNormal(xm = temp, samplename = samples[i], cores = 8, parallel = TRUE)
out2 <- quackBeta(xm = temp, samplename = samples[i], cores = 8, parallel = TRUE)
out3 <- quackBetaBinom(xm = temp, samplename = samples[i], cores = 8, parallel = TRUE)
allout <- rbind(out1, out2, out3)
write.csv(allout, file = paste0("./nQuack/04_output/", samples[i], "_denoised_output.csv"), row.names = FALSE)
}
```

I get this error output that I suspect comes from the `quackBeta()` command:

```
 		 <(.)__ <(.)__ <(-)__
 		  (___/  (___/  (___/  nQuack-in-progress
parallel set to TRUE
Free Model Skipped. Log-likelihood ratio will not be included
Calculating likelihood of each mixture with a normal distibution.
Calculating likelihood of each mixture with a normal+uniform distibution.
 		 <(.)__ <(.)__ <(-)__
 		  (___/  (___/  (___/  nQuack-in-progress
parallel set to TRUE
Free Model Skipped. Log-likelihood ratio will not be included
**Calculating likelihood of each mixture with a beta distibution.
Error in { : 
  task 2 failed - "function cannot be evaluated at initial parameters"
Calls: quackBeta -> %dopar% -> <Anonymous>
Execution halted**
```

What can I do?

Thanks
Rowan

**Comment by mgaynor1** [comment]
Hi there. Based on what you shared, I don't know why this error is occurring. 

Some possibilities:
1. Have you plotted your denoise_processed data? Potentially, you may have removed too much data and there isn't enough to begin the E-step. Is this error consistent among samples?
2.  What system are you running this on? Can you also share your version of R and version of foreach? The error message is not from nQuack functions, the error is either from foreach or it is from base R. 
3. Can you run this function not in parallel without issue?

**Comment by RSchley** [comment]
Hi Shelly, in answer to your questions:

1. I have plotted the denoised data, and it looked fine.  The error is indeed consistent among samples, both 'noisy' and 'denoised' from nQuire.

2. I am using 'R version 4.1.1 (2021-08-10) -- "Kick Things"'. Foreach is v.1.5.2.

3. Yes, this error persists with and without parallel.

I have since tried running the data preparation from BAM files (as in your nice tutorial: https://mlgaynor.com/nQuack/articles/BasicExample.html#prepare-data), rather than from my old nQuire output, and it is working beautifully. Strangely, this gives a similar amount of data to that produced by nQuire, so I am not quite sure why the beta distribution model wasn't working.

Thanks for such a quick response.

**Comment by mgaynor1** [comment]
Well, I am glad to hear it works on the BAM files processed with nQuack. But, would love to figure out what this issue was! 

1. Can you run `sessionInfo()` and share the output?

2. Would you mind emailing me a file processed with nQuire so I can see if I can recreate the issue on my end? I'm wondering if there is an issue with [src/datahelper.cpp](https://github.com/mgaynor1/nQuack/blob/f1db9b1fa6d89ac7e7770ec4f5a57e1ddff61059/src/datahelper.cpp#L13) and how I convert the nQuire input. 

Glad you were able to make this work for your samples!

**Comment by RSchley** [comment]
Sure, `sessionInfo()` outputs this:

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Rocky Linux 8.10 (Green Obsidian)

Matrix products: default
BLAS:   /mnt/shared/scratch/rschley/apps/conda/lib/libblas.so.3.9.0
LAPACK: /mnt/shared/scratch/rschley/apps/conda/lib/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] kableExtra_1.4.0 dplyr_1.1.4      nQuack_1.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.13            compiler_4.1.1         pillar_1.9.0
 [4] iterators_1.0.14       tools_4.1.1            digest_0.6.37
 [7] evd_2.3-7.1            viridisLite_0.4.2      evaluate_0.23
[10] lifecycle_1.0.4        tibble_3.2.1           pkgconfig_2.0.3
[13] rlang_1.1.3            foreach_1.5.2          rstudioapi_0.16.0
[16] cli_3.6.2              parallel_4.1.1         xfun_0.43
[19] RcppArmadillo_14.0.2-1 fastmap_1.1.1          xml2_1.3.6
[22] stringr_1.5.1          knitr_1.46             systemfonts_1.0.5
[25] generics_0.1.3         vctrs_0.6.5            globals_0.16.3
[28] stats4_4.1.1           tidyselect_1.2.1       svglite_2.1.3
[31] glue_1.7.0             data.table_1.16.2      listenv_0.9.1
[34] R6_2.5.1               fansi_1.0.6            parallelly_1.38.0
[37] rmarkdown_2.26         magrittr_2.0.3         scales_1.3.0
[40] codetools_0.2-20       htmltools_0.5.8.1      RcppProgress_0.4.2
[43] truncdist_1.0-2        colorspace_2.1-0       future_1.34.0
[46] utf8_1.2.4             stringi_1.8.4          munsell_0.5.1
[49] doParallel_1.0.17

```

**Comment by mgaynor1** [comment]
Based on email - seems to be an issue with input data. Unsure if the nQuire data output differed or if there is an issue with one of nQuack's input functions. Closing this issue due to inability to repeat the error.
